services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./insert_data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - skladify-net
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=postgres pg_isready --username=warehouse_user --dbname=warehouse_db"]
      interval: 1s
      timeout: 1s
      retries: 10

  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: warehouse_db
      DB_USER: warehouse_user
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skladify-net

volumes:
  postgres_data:

networks:
  skladify-net:
